
flib_version=1.0.0-SNAPSHOT

mod_id=oceanfloor
curse_slug=ocean-floor-clay-sand-and-dirt
curse_id=231837
mod_version=1.1.0
mod_name=oceanfloor
mod_group_id=com.lothrazar.oceanfloor
mod_license=SeeGithub
mod_authors=Lothrazar
mod_description=mod
