
#####################################################################################
#Features
#####################################################################################
[oceanfloor]

	#####################################################################################
	# Gravel + Coarse Dirt spawn in the stone caves below ocean-type biomes
	#####################################################################################
	[oceanfloor.gravel]
		#Patch size
		#Range: 0 ~ 64
		size = 16
		#Spread
		#Range: 1 ~ 100
		spread = 16

	#####################################################################################
	# Sand spawns in gravel floors of ocean-type biomes
	#####################################################################################
	[oceanfloor.sand]
		#Patch size
		#Range: 0 ~ 64
		size = 22
		#Spread
		#Range: 1 ~ 100
		spread = 45

	#####################################################################################
	# Dirt spawns in spand an gravel floors of ocean-type biomes
	#####################################################################################
	[oceanfloor.dirt]
		#Patch size
		#Range: 0 ~ 64
		size = 16
		#Spread
		#Range: 1 ~ 100
		spread = 15

	#####################################################################################
	# Clay spawns in sand and gravel floors of ocean-type biomes
	#####################################################################################
	[oceanfloor.clay]
		#Patch size
		#Range: 0 ~ 64
		size = 32
		#Spread
		#Range: 1 ~ 100
		spread = 75

